services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  flask-app:
    build: .
    env_file: ./.env
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis

  consumer:
    build: .
    env_file: ./.env
    command: python consumer.py
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis