version: "3.7"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5673:5672"
      - "15673:15672"

  consumer:
    build: .
    command: ["python", "consumer.py"]
    depends_on:
      - rabbitmq
